[tool.poetry]
name = "mailing-management-service"
version = "0.1.0"
description = ""
authors = ["maksim <m.merkulovdodo@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.7"
python-dotenv = "^1.0.1"
black = "^25.1.0"
flake8 = "^7.1.2"
psycopg2-binary = "^2.9.10"
pillow = "^11.1.0"
certifi = "^2025.1.31"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
