# Generated by Django 5.1.7 on 2025-04-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0003_alter_mailing_options_alter_mailingrecipient_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="failed_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mailing",
            name="successful_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mailing",
            name="total_messages_sent",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
